version: '3'

networks:
  prometheus-lab:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    labels:
      container_group: services-monitoring
#    deploy:
#        resources:
#          limits:
#            cpus: '1'
#            memory: 256M
#          reservations:
#            cpus: '0.6'
#            memory: 128M
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=168h'
      - '--web.enable-lifecycle'
    restart: on-failure
    ports: 
      - '9090:9090'
    networks:
      - prometheus-lab