scrape_configs:

- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets: ['IP:8080']
  metric_relabel_configs:
      - source_labels: [container_label_container_group]
        target_label: container_group

- job_name: NOME_DO_HOST
  scrape_interval: 5s
  static_configs:
    - targets: ['IP:9100']