version: '3'

#networks:

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./plugins:/var/lib/grafana/plugins
    restart: on-failure
    ports:
      - '3000:3000' 