version: '3'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    labels:
      container_group: services-monitoring
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: [ "--allow_dynamic_housekeeping=false" ]